### PR TITLE
Fix amazon links and add image after form

### PR DESCRIPTION
**Pull request by AndrewLester**
Ready for merge

### CODE REVIEW

**Comment by AndrewLester** [comment]
@ErikBoesen

**Comment by ErikBoesen** [comment]
@AndrewLester in the future just merge your own PRs (assuming you've tested and all) and I'll look them over later. That way my dad doesn't have to badger me to merge haha

**Comment by AndrewLester** [comment]
I don't think I can merge my PRs.

**Comment by ErikBoesen** [comment]
Whoops! Made you an owner.

**Pull request merged**
